---
defaults: &defaults
  working_directory: /go/src/github.com/nathandines/forge
  docker:
    - image: circleci/golang:latest

version: 2
jobs:
  build:
    <<: *defaults

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout

      - run: &install_dep
          name: Install dep
          command: command -v dep >/dev/null || curl 'https://raw.githubusercontent.com/golang/dep/master/install.sh' | sh

      - run: make deps

      - run: make lint

      # unit testing
      - run: mkdir -p "$TEST_RESULTS"
      - run: go get github.com/jstemmer/go-junit-report
      - run: |
          trap 'go-junit-report <"${TEST_RESULTS}/go-test.out" > "${TEST_RESULTS}/go-test-report.xml"' EXIT
          make test | tee "${TEST_RESULTS}/go-test.out"

      # smoke test
      - run: make build
      - run: ./bin/forge --version

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results

      - persist_to_workspace:
          root: '.'
          paths:
            - bin
            - vendor

  release-github:
    <<: *defaults

    environment:
      CGO_ENABLED: '0'

    steps:
      - checkout

      - attach_workspace:
          at: '.'

      - run: &validate_tag_version
          name: Validate Tag Version
          command: |
            forge_version="$(./bin/forge --version | grep -Po 'v\d+(?:\.\d+){2}(?:-[a-z]+\d?)?$')"
            if [[ "$CIRCLE_TAG" != "$forge_version" ]]; then
              echo "Tag version \"${CIRCLE_TAG}\" does not match binary version \"${forge_version}\""
              exit 1
            fi
            mkdir release

      - run:
          name: Build - Linux (32-bit)
          environment:
            GOOS: linux
            GOARCH: '386'
          command: &build_cmd |
            make deps
            go build -v -o "release/forge_${CIRCLE_TAG}_${GOOS}_${GOARCH}${FILEEXT}"

      - run:
          name: Build - Linux (64-bit)
          environment:
            GOOS: linux
            GOARCH: amd64
          command: *build_cmd

      - run:
          name: Build - Windows (32-bit)
          environment:
            GOOS: windows
            GOARCH: '386'
            FILEEXT: .exe
          command: *build_cmd

      - run:
          name: Build - Windows (64-bit)
          environment:
            GOOS: windows
            GOARCH: amd64
            FILEEXT: .exe
          command: *build_cmd

      - run:
          name: Build - Darwin (64-bit)
          environment:
            GOOS: darwin
            GOARCH: amd64
          command: *build_cmd

      - run: go get github.com/tcnksm/ghr
      - run:
          name: Release to GitHub
          command: |
            if (printf "$CIRCLE_TAG" | grep -Pq -- '-[a-z]+\d?$'); then
              PRERELEASE='-prerelease'
            fi
            ghr -u "$CIRCLE_PROJECT_USERNAME" -r "$CIRCLE_PROJECT_REPONAME" -replace $PRERELEASE "$CIRCLE_TAG" release

  release-docker:
    <<: *defaults

    steps:
      - checkout

      - attach_workspace:
          at: '.'

      - run: *validate_tag_version

      - setup_remote_docker

      - run:
          name: Build container and Release to Docker Hub
          command: |
            DOCKER_REPO="${CIRCLE_PROJECT_USERNAME}/forge"
            docker build -t "${DOCKER_REPO}:${CIRCLE_TAG}" .
            docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
            docker push "${DOCKER_REPO}:${CIRCLE_TAG}"
            # If not a pre-release version, tag as latest
            if ! (printf "$CIRCLE_TAG" | grep -Pq -- '-[a-z]+\d?$'); then
              docker tag "${DOCKER_REPO}:${CIRCLE_TAG}" "${DOCKER_REPO}:latest"
              docker push "${DOCKER_REPO}:latest"
            fi

  release-homebrew:
    docker:
      - image: linuxbrew/linuxbrew:latest

    environment:
      GIT_AUTHOR_NAME: &git_name Nathan Dines
      GIT_COMMITTER_NAME: *git_name
      EMAIL: nath@ndin.es

    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - '5d:60:98:cf:bb:eb:cf:87:06:44:e7:18:9f:61:87:b6'
      - run:
          name: Release to Homebrew Tap
          command: make brew-release FORGE_VERSION="$CIRCLE_TAG"

  release-chocolatey:
    docker:
      - image: linuturk/mono-choco:latest

    steps:
      - checkout

      - attach_workspace:
          at: '.'

      - run:
          name: Install make
          command: |
            apt-get update
            apt-get install make

      - run:
          name: Release to Chocolatey
          command: make choco-release FORGE_VERSION="$CIRCLE_TAG" LICENSE_COMMIT="$CIRCLE_SHA1"

workflows:
  version: 2
  build-n-release:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - release-github:
          requires:
            - build
          filters:
            tags:
              only: &version_tag /^v\d+(?:\.\d+){2}(?:-[a-z]+\d?)?$/
            branches:
              ignore: /.*/
      - release-docker:
          context: dockerhub
          requires:
            - build
          filters:
            tags:
              only: *version_tag
            branches:
              ignore: /.*/
      - release-homebrew:
          requires:
            - release-github
          filters:
            tags:
              only: /^v\d+(?:\.\d+){2}$/
            branches:
              ignore: /.*/
      - release-chocolatey:
          context: chocolatey
          requires:
            - release-github
          filters:
            tags:
              only: /^v\d+(?:\.\d+){2}$/
            branches:
              ignore: /.*/
  nightly:
    triggers:
      - schedule:
          cron: "37 14 * * *"
          filters:
            branches:
              only:
                - master
                - develop
    jobs:
      - build
